import {
    agent1,agent2,agent3,agent4,agent5,agent6,agent7
}
from "../../core/Images";
export const agentListing = [
    {
      id          : 1,
      image       : agent1,
      name        : "Michael Squeo",
      designation : "Mortgage Broker",
      phone1      : "(416) 827-2626",
      phone2      : "6476575455",
      email       : "test@yopmail.com",
      twitter     : "www.twitter.com",
      facebook    : "www.facebook.com",
      instagram   : "www.instagram.com",
    },
    {
        id          : 2,
        image       : agent2,
        name        : "Jenivia Selvarajah",
        designation : "Agent",
        phone1      : "(416) 827-2626",
        phone2      : "6476575455",
        email       : "test@yopmail.com",
        twitter     : "www.twitter.com",
        facebook    : "www.facebook.com",
        instagram   : "www.instagram.com",
      },
      {
        id          : 3,
        image       : agent3,
        name        : "Teresa Berardi",
        designation : "Agent",
        phone1      : "(416) 827-2626",
        phone2      : "6476575455",
        email       : "test@yopmail.com",
        twitter     : "www.twitter.com",
        facebook    : "www.facebook.com",
        instagram   : "www.instagram.com",
      },
      {
        id          : 4,
        image       : agent4,
        name        : "Rania Warde",
        designation : "Agent",
        phone1      : "(416) 827-2626",
        phone2      : "6476575455",
        email       : "test@yopmail.com",
        twitter     : "www.twitter.com",
        facebook    : "www.facebook.com",
        instagram   : "www.instagram.com",
      },
      {
        id          : 5,
        image       : agent5,
        name        : "Gabrijela Mihajlovic",
        designation : "Agent",
        phone1      : "(416) 827-2626",
        phone2      : "6476575455",
        email       : "test@yopmail.com",
        twitter     : "www.twitter.com",
        facebook    : "www.facebook.com",
        instagram   : "www.instagram.com",
      },
      {
        id          : 6,
        image       : agent6,
        name        : "Winston Smith",
        designation : "Agent",
        phone1      : "(416) 827-2626",
        phone2      : "6476575455",
        email       : "test@yopmail.com",
        twitter     : "www.twitter.com",
        facebook    : "www.facebook.com",
        instagram   : "www.instagram.com",
      },
      {
        id          : 7,
        image       : agent7,
        name        : "Manpreet Bhinder",
        designation : "Agent",
        phone1      : "(416) 827-2626",
        phone2      : "6476575455",
        email       : "test@yopmail.com",
        twitter     : "www.twitter.com",
        facebook    : "www.facebook.com",
        instagram   : "www.instagram.com",
      },
      {
        id          : 8,
        image       : agent7,
        name        : "Joan Delaney",
        designation : "Agent",
        phone1      : "(416) 827-2626",
        phone2      : "6476575455",
        email       : "test@yopmail.com",
        twitter     : "www.twitter.com",
        facebook    : "www.facebook.com",
        instagram   : "www.instagram.com",
      },
  ];